Module-0 Task-1
js-tasks-ru/jsbasic-20220711_merichiko pull request #1
Opened 2022-07-12 12:59 UTC by Murvedra

2022-07-12 12:59 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2022-07-12 16:32 UTC, SinimaWath requested changes

2022-07-12 16:32 UTC, SinimaWath commented on 0-module/1-task/index.js
> +alert( x + y );
Все ок. Но из-за задач, надо убирать код для тестирования

в файле, index.js - должена оставаться лишь функция, без лишнего кода

2022-07-18 13:03 UTC, SinimaWath commented on 0-module/1-task/index.js
> +alert( x + y );
Надо править :)

2022-07-18 13:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-18 15:26 UTC, Murvedra commented on 0-module/1-task/index.js
> +alert( x + y );
Подумала, что это на будущее. Если я только отправила первого урока решения, могу же со вторым вместе отправить исправленный нулевой урок? Чтобы по 10 раз не присылать

2022-07-19 14:30 UTC, SinimaWath requested changes

2022-07-19 14:30 UTC, SinimaWath commented on 0-module/1-task/index.js
> +let x = sum(1,1), y = sum(2,5);
Из задач, надо убирать код для тестирования. Оставь толко одну функцию

2022-07-19 14:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-20 11:55 UTC, SinimaWath approved these changes
все ок

2022-07-20 11:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-20 11:56 UTC, merged